---
abstract: 'A fast disk usage counter (du) with XS'
author:
  - 'Ryo Okamoto, C<< <ryo at aquahill dot net> >>'
build_requires:
  ExtUtils::CBuilder: 0
  Scalar::Util: 0
  Test::LeakTrace: 0
  Test::More: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Filesys-DiskUsage-Fast
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Filesys::DiskUsage::Fast:
    file: lib/Filesys/DiskUsage/Fast.pm
    version: 0.03
resources:
  repository: ssh://ryo@repos.aquahill.net/var/repos/p5-filesys-diskusage-fast
version: 0.03
x_contributors:
  - 'Ryo Okamoto <ryo@aquahill.net>'
